# Generated by Django 2.2.18 on 2021-03-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=191)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('class_rep', models.CharField(default='Principal', max_length=100)),
                ('class_logo', models.ImageField(null=True, upload_to='class_logo')),
            ],
            options={
                'verbose_name_plural': 'formclasses',
            },
        ),
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=191)),
                ('slug', models.SlugField(default='inzu', max_length=200)),
                ('hostel_logo', models.ImageField(null=True, upload_to='hostel_logo')),
            ],
            options={
                'verbose_name_plural': 'Hostels',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('admission_number', models.CharField(max_length=191)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=191)),
                ('boarding', models.BooleanField(default=False)),
                ('parent_name', models.CharField(max_length=191)),
                ('parent_mobile_number', models.CharField(max_length=191)),
                ('dob', models.CharField(max_length=191)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('student_photo', models.ImageField(upload_to='student_picture')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('form_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Formclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBoarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Hostels')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
